### ISSUE TITLE
rollbarExtensionIsActive Do not work with TYPO3 8.x

### ISSUE THREAD

**Issue by lochmueller** [castiron/typo3-plugin-rollbar#1]
Hey guys,

the function do not work with the new PackageStats file, because there are only "packagePath" in there and no "state" anymore. Perhaps something like this:
```return !isset($rollbarConfig['state']) ? true : ($rollbarConfig['state'] === 'active');```

Regards,
Tim

**Comment by gblair** [comment]
Thanks @lochmueller is the idea with the updated `PackageStates.php` that a package will only be listed when it's installed and active? I can modify the thing to account for that.

**Comment by lochmueller** [comment]
right. Since TYPO3 8.x is the extension installed, if there is a entry in the PackageStates. If there is no entry, the extension is not installed.

**Comment by gblair** [comment]
Oops fixed this for TYPO3 8, but I guess _really wanting_ it to work in TYPO3 6 is not good enough. One sec.
